--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.791.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 22/05/2022 4:04:21 AM
-- Server version: 8.0.29
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS employee_management;

CREATE DATABASE employee_management
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE employee_management;

--
-- Create table `roles`
--
CREATE TABLE roles (
  RoleID int NOT NULL AUTO_INCREMENT,
  RoleName varchar(50) DEFAULT NULL,
  Description text DEFAULT NULL,
  PermissionDetail longtext binary CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  IsSystem tinyint(1) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (RoleID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 12,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb3,
COLLATE utf8_general_ci;

--
-- Create table `organizationunits`
--
CREATE TABLE organizationunits (
  OrganizationUnitID int NOT NULL AUTO_INCREMENT,
  OrganizationUnitCode varchar(255) DEFAULT NULL,
  OrganizationUnitName varchar(255) DEFAULT NULL,
  ParentID int DEFAULT NULL,
  OrgCode text DEFAULT NULL,
  Address text DEFAULT NULL,
  Description text DEFAULT NULL,
  IsSystem tinyint(1) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (OrganizationUnitID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 31,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb3,
COLLATE utf8_general_ci;

--
-- Create table `jobpositions`
--
CREATE TABLE jobpositions (
  JobPositionID int NOT NULL AUTO_INCREMENT,
  JobPositionName varchar(50) DEFAULT NULL,
  JobPositionCode varchar(255) DEFAULT NULL,
  OrganizationUnitID int DEFAULT NULL,
  OrganizationUnitName varchar(50) DEFAULT NULL,
  Description text DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (JobPositionID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 14,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb3,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE jobpositions
ADD CONSTRAINT FK_jobpositions_OrganizationUnitID FOREIGN KEY (OrganizationUnitID)
REFERENCES organizationunits (OrganizationUnitID);

--
-- Create table `users`
--
CREATE TABLE users (
  UserID int NOT NULL AUTO_INCREMENT,
  EmployeeCode varchar(50) DEFAULT NULL,
  FullName varchar(50) DEFAULT NULL,
  PhoneNumber varchar(50) DEFAULT NULL,
  Email varchar(50) DEFAULT NULL,
  UserEmail varchar(50) DEFAULT NULL,
  IsUser tinyint(1) DEFAULT NULL,
  IdentityNumber varchar(50) DEFAULT NULL,
  IdentityDate date DEFAULT NULL,
  IdentityPlace text DEFAULT NULL,
  GenderID int DEFAULT NULL,
  GenderName varchar(50) DEFAULT NULL,
  BirthDay date DEFAULT NULL,
  EthicID int DEFAULT NULL,
  EthicName varchar(50) DEFAULT NULL,
  ReligionID int DEFAULT NULL,
  ReligionName varchar(50) DEFAULT NULL,
  OrganizationUnitID int DEFAULT NULL,
  OrganizationUnitName varchar(50) DEFAULT NULL,
  JobPositionID int DEFAULT NULL,
  JobPositionName varchar(50) DEFAULT NULL,
  EmployeeStatusID int DEFAULT NULL,
  EmployeeStatusName varchar(50) DEFAULT NULL,
  UserStatusID int DEFAULT NULL,
  UserStatusName varchar(50) DEFAULT NULL,
  EmployeeNatureID int DEFAULT NULL,
  HireDate date DEFAULT NULL,
  ReceiveDate date DEFAULT NULL,
  OutDate date DEFAULT NULL,
  CurrentAddress text DEFAULT NULL,
  NativeAddress text DEFAULT NULL,
  BasicSalary double DEFAULT NULL,
  InsuranceSalary double DEFAULT NULL,
  IsDeleted tinyint(1) DEFAULT NULL,
  CreatedDate date DEFAULT NULL,
  CreatedBy varchar(50) DEFAULT NULL,
  ModifiedDate date DEFAULT NULL,
  ModifiedBy varchar(50) DEFAULT NULL,
  PassWord varchar(255) DEFAULT NULL,
  IsAdmin tinyint(1) DEFAULT NULL,
  IsSystemAdmin tinyint(1) DEFAULT NULL,
  EmployeeNatureName varchar(255) DEFAULT NULL,
  PRIMARY KEY (UserID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 52,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8mb3,
COLLATE utf8_general_ci;

--
-- Create table `user_role`
--
CREATE TABLE user_role (
  UserRoleID int NOT NULL AUTO_INCREMENT,
  RoleID int DEFAULT NULL,
  UserID int DEFAULT NULL,
  UserName varchar(255) DEFAULT NULL,
  OrganizationUnitID int DEFAULT NULL,
  OrganizationUnitName varchar(255) DEFAULT NULL,
  Status int DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (UserRoleID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb3,
COLLATE utf8_general_ci;

--
-- Create index `FK_user_role_RoleID2` on table `user_role`
--
ALTER TABLE user_role
ADD INDEX FK_user_role_RoleID2 (RoleID);

--
-- Create foreign key
--
ALTER TABLE user_role
ADD CONSTRAINT FK_user_role_RoleID FOREIGN KEY (RoleID)
REFERENCES roles (RoleID);

--
-- Create foreign key
--
ALTER TABLE user_role
ADD CONSTRAINT FK_user_role_UserID FOREIGN KEY (UserID)
REFERENCES users (UserID);

--
-- Create table `contracts`
--
CREATE TABLE contracts (
  ContractID int NOT NULL AUTO_INCREMENT,
  ContractNo varchar(255) DEFAULT NULL,
  ContractName varchar(255) DEFAULT NULL,
  UserID int DEFAULT NULL,
  ContractPeriodID int DEFAULT NULL,
  ContractPeriodName varchar(50) DEFAULT NULL,
  FromDate date DEFAULT NULL,
  ToDate date DEFAULT NULL,
  BasicSalary double DEFAULT NULL,
  InsuranceSalary double DEFAULT NULL,
  IsDeleted tinyint(1) DEFAULT NULL,
  CreatedDate date DEFAULT NULL,
  CreatedBy varchar(50) DEFAULT NULL,
  ModifiedDate date DEFAULT NULL,
  ModifiedBy varchar(50) DEFAULT NULL,
  ContractTypeID int DEFAULT NULL,
  ContractTypeName varchar(50) DEFAULT NULL,
  OrganizationUnitID int DEFAULT NULL,
  OrganizationUnitName varchar(50) DEFAULT NULL,
  JobPositionID int DEFAULT NULL,
  JobPositionName varchar(50) DEFAULT NULL,
  FullName varchar(255) DEFAULT NULL,
  StatusID int DEFAULT NULL,
  StatusName varchar(255) DEFAULT NULL,
  PRIMARY KEY (ContractID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 57,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb3,
COLLATE utf8_general_ci,
COMMENT = 'hợp đồng';

--
-- Create foreign key
--
ALTER TABLE contracts
ADD CONSTRAINT FK_contracts_UserID FOREIGN KEY (UserID)
REFERENCES users (UserID);

--
-- Create table `user_option`
--
CREATE TABLE user_option (
  ID int NOT NULL AUTO_INCREMENT,
  UserID int DEFAULT NULL,
  `Option` longtext DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb3,
COLLATE utf8_general_ci;

--
-- Create table `sessions`
--
CREATE TABLE sessions (
  SessionID char(36) NOT NULL,
  UserID int DEFAULT NULL,
  Token text DEFAULT NULL,
  Expire bigint DEFAULT NULL,
  PRIMARY KEY (SessionID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb3,
COLLATE utf8_general_ci;

-- 
-- Dumping data for table roles
--
INSERT INTO roles VALUES
(7, 'QTHT', 'Quản trị hệ thống', 'View;Modified', NULL, NULL, NULL, NULL, NULL),
(8, 'HR', 'Nhân sự', 'View;Modified', NULL, NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table organizationunits
--
INSERT INTO organizationunits VALUES
(1, NULL, 'Văn phòng tổng công ty', NULL, NULL, '826 Campus Place, Salunga, Pennsylvania, 4458', 'Văn phòng tổng công ty', NULL, NULL, NULL, NULL, NULL),
(2, NULL, 'Khối sản xuất', 1, NULL, '180 Rutherford Place, Libertytown, Connecticut, 8252', 'Bao gồm Trung tâm phát triển phần mềm và Viện Nghiên cứu', NULL, NULL, NULL, NULL, NULL),
(3, NULL, 'Trung tâm phát triển phần mềm', 2, NULL, '747 Jefferson Avenue, Bloomington, South Carolina, 6064', 'Phát triển phần mềm: web app, desktop app', NULL, NULL, NULL, NULL, NULL),
(4, NULL, 'Viện nghiên cứu và đào tạo', 2, NULL, '230 Carlton Avenue, Hiwasse, Kansas, 531', 'Nghiên cứu các công nghệ: AI, Big Data', NULL, NULL, NULL, NULL, NULL),
(5, NULL, 'Phòng nhân sự', 1, NULL, '375 Seigel Court, Jenkinsville, Nevada, 9112', NULL, NULL, NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(51, 'NV0001', 'Nguyễn Quốc Đạt', NULL, 'nqdat@yahoo.com', NULL, 0, '0101010101', '2017-01-15', 'Hải Dương', 1, NULL, '2000-10-11', NULL, 'Không', NULL, 'Kinh', 1, NULL, 11, NULL, 0, NULL, 0, NULL, 0, '2022-05-21', NULL, NULL, 'Hà Nội', 'Hải Dương', NULL, NULL, 0, '2022-05-22', NULL, '2022-05-22', NULL, NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table user_role
--
INSERT INTO user_role VALUES
(7, 7, 51, NULL, 1, NULL, NULL, NULL, '2022-05-22 03:04:04', NULL, NULL);

-- 
-- Dumping data for table user_option
--
-- Table employee_management.user_option does not contain any data (it is empty)

-- 
-- Dumping data for table sessions
--
-- Table employee_management.sessions does not contain any data (it is empty)

-- 
-- Dumping data for table jobpositions
--
INSERT INTO jobpositions VALUES
(11, 'Lập trình viên', 'VT0001', 3, NULL, NULL, NULL, NULL, '2022-05-22 03:13:42', NULL),
(12, 'Chuyên viên nghiên cứu công nghệ', 'VT0002', 3, NULL, NULL, NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table contracts
--
INSERT INTO contracts VALUES
(56, 'HĐ0001', 'Hợp đồng lập trình viên', 51, 0, NULL, '2022-05-20', '2022-05-21', 9500000, 9000000, NULL, NULL, NULL, '2022-05-22', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, 0, NULL);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;